### ISSUE TITLE
Is there a bundle for this?

### ISSUE THREAD

**Issue by tacman** [zenstruck/filesystem#101]
I see a reference to Bundle under Symfony Integration, is that a placeholder for a future bundle, or is there one?

If you do create a bundle for this, please consider making it a Symfony ^6.1+ bundle that extends AbstractBundle and uses the much easier configuration.  This is mostly because I look to your libraries and bundles to see best practices for Symfony coding.   Thanks!

**Comment by kbond** [comment]
Hey @tacman, that is the bundle, you just have to enable/configure it manually (no recipe yet).

This bundle has a complex extension/configuration so keeping it separate makes sense I think.
